# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alisa/Documents/Lab05

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alisa/Documents/Lab05

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alisa/Documents/Lab05/CMakeFiles /home/alisa/Documents/Lab05/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alisa/Documents/Lab05/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ARPtools

# Build rule for target.
ARPtools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ARPtools
.PHONY : ARPtools

# fast build rule for target.
ARPtools/fast:
	$(MAKE) -f CMakeFiles/ARPtools.dir/build.make CMakeFiles/ARPtools.dir/build
.PHONY : ARPtools/fast

ARPLib.o: ARPLib.cpp.o

.PHONY : ARPLib.o

# target to build an object file
ARPLib.cpp.o:
	$(MAKE) -f CMakeFiles/ARPtools.dir/build.make CMakeFiles/ARPtools.dir/ARPLib.cpp.o
.PHONY : ARPLib.cpp.o

ARPLib.i: ARPLib.cpp.i

.PHONY : ARPLib.i

# target to preprocess a source file
ARPLib.cpp.i:
	$(MAKE) -f CMakeFiles/ARPtools.dir/build.make CMakeFiles/ARPtools.dir/ARPLib.cpp.i
.PHONY : ARPLib.cpp.i

ARPLib.s: ARPLib.cpp.s

.PHONY : ARPLib.s

# target to generate assembly for a file
ARPLib.cpp.s:
	$(MAKE) -f CMakeFiles/ARPtools.dir/build.make CMakeFiles/ARPtools.dir/ARPLib.cpp.s
.PHONY : ARPLib.cpp.s

ARPOperate.o: ARPOperate.cpp.o

.PHONY : ARPOperate.o

# target to build an object file
ARPOperate.cpp.o:
	$(MAKE) -f CMakeFiles/ARPtools.dir/build.make CMakeFiles/ARPtools.dir/ARPOperate.cpp.o
.PHONY : ARPOperate.cpp.o

ARPOperate.i: ARPOperate.cpp.i

.PHONY : ARPOperate.i

# target to preprocess a source file
ARPOperate.cpp.i:
	$(MAKE) -f CMakeFiles/ARPtools.dir/build.make CMakeFiles/ARPtools.dir/ARPOperate.cpp.i
.PHONY : ARPOperate.cpp.i

ARPOperate.s: ARPOperate.cpp.s

.PHONY : ARPOperate.s

# target to generate assembly for a file
ARPOperate.cpp.s:
	$(MAKE) -f CMakeFiles/ARPtools.dir/build.make CMakeFiles/ARPtools.dir/ARPOperate.cpp.s
.PHONY : ARPOperate.cpp.s

fakeARPTool.o: fakeARPTool.cpp.o

.PHONY : fakeARPTool.o

# target to build an object file
fakeARPTool.cpp.o:
	$(MAKE) -f CMakeFiles/ARPtools.dir/build.make CMakeFiles/ARPtools.dir/fakeARPTool.cpp.o
.PHONY : fakeARPTool.cpp.o

fakeARPTool.i: fakeARPTool.cpp.i

.PHONY : fakeARPTool.i

# target to preprocess a source file
fakeARPTool.cpp.i:
	$(MAKE) -f CMakeFiles/ARPtools.dir/build.make CMakeFiles/ARPtools.dir/fakeARPTool.cpp.i
.PHONY : fakeARPTool.cpp.i

fakeARPTool.s: fakeARPTool.cpp.s

.PHONY : fakeARPTool.s

# target to generate assembly for a file
fakeARPTool.cpp.s:
	$(MAKE) -f CMakeFiles/ARPtools.dir/build.make CMakeFiles/ARPtools.dir/fakeARPTool.cpp.s
.PHONY : fakeARPTool.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ARPtools"
	@echo "... edit_cache"
	@echo "... ARPLib.o"
	@echo "... ARPLib.i"
	@echo "... ARPLib.s"
	@echo "... ARPOperate.o"
	@echo "... ARPOperate.i"
	@echo "... ARPOperate.s"
	@echo "... fakeARPTool.o"
	@echo "... fakeARPTool.i"
	@echo "... fakeARPTool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

